name: build

on:
  push:
    branches:
      - '**'
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Use Node.js
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      - run: yarn build

      - uses: actions/upload-artifact@694cdabd8bdb0f10b2cea11669e1bf5453eed0a6 # v4.2.0
        with:
          name: artifacts
          path: bin/

  release:
    needs: build
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
        with:
          name: artifacts
          path: bin

      - name: prepare
        run: |
          echo "VERSION=$(echo ${VERSION:1})" >> $GITHUB_ENV
        env:
          VERSION: ${{ github.ref_name }}

      - name: github release
        uses: ncipollo/release-action@6c75be85e571768fa31b40abf38de58ba0397db5 # v1.13.0
        with:
          allowUpdates: true
          body: See https://github.com/visualon/mathjax-sp/blob/main/CHANGELOG.md for changes
          commit: ${{ github.sha }}
          name: ${{ env.VERSION }}
          tag: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: bin/*.*
          artifactErrorsFailBuild: true

      - name: nuget
        run: |
          find bin -name '*.nupkg' -exec dotnet nuget push {} -k ${GITHUB_TOKEN} -s ${GITHUB_SOURCE} --skip-duplicate --force-english-output \;
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_SOURCE: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
