name: build

on:
  push:
    branches:
      - '**'
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      - name: Use Node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      - run: yarn build

      - uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # tag=v3.1.1
        with:
          name: artifacts
          path: bin/

  release:
    needs: build
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7 # tag=v3.0.1
        with:
          name: artifacts
          path: bin

      - name: prepare
        run: |
          echo "VERSION=$(echo ${VERSION:1})" >> $GITHUB_ENV
        env:
          VERSION: ${{ github.ref_name }}

      - name: github release
        uses: ncipollo/release-action@18eadf9c9b0f226f47f164f5373c6a44f0aae169 # tag=v1.11.2
        with:
          allowUpdates: true
          body: See https://github.com/visualon/mathjax-sp/blob/main/CHANGELOG.md for changes
          commit: ${{ github.sha }}
          name: ${{ env.VERSION }}
          tag: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: bin/*.*
          artifactErrorsFailBuild: true

      - name: nuget
        run: |
          find bin -name '*.nupkg' -exec dotnet nuget push {} -k ${GITHUB_TOKEN} -s ${GITHUB_SOURCE} --skip-duplicate --force-english-output \;
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_SOURCE: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
